name: publish docker images

on:
  push:
    branches:
    - test
    paths:
    - '.github/workflows/publish_docker_images.yml'
    - '.github/dockerfiles/**'

permissions:
  contents: read

env:
  REGISTRY: ghcr.io/hvdijk

jobs:

  publish-docker-images-x86-64:
    runs-on: ubuntu-latest
    permissions:
      attestations: write
      id-token: write
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push the Docker images
      run: |
        for DOCKERFILE in ${{ github.workspace }}/.github/dockerfiles/Dockerfile_*x86-64 ; do
          VERSION=${DOCKERFILE##*_}
          docker build . -f $DOCKERFILE --tag $REGISTRY/ock_ubuntu_$VERSION:latest
          docker push $REGISTRY/ock_ubuntu_$VERSION:latest
        done

  publish-docker-images-aarch64:
    runs-on: ubuntu-22.04-arm
    permissions:
      attestations: write
      id-token: write
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push the Docker images
      run: |
        DOCKERFILE=${{ github.workspace }}/.github/dockerfiles/Dockerfile_22.04-aarch64
        VERSION=${DOCKERFILE##*_}
        docker build . -f $DOCKERFILE --tag $REGISTRY/ock_ubuntu_$VERSION:latest
        docker push $REGISTRY/ock_ubuntu_$VERSION:latest
